export enum EnumErrors {
    ADDING_DOCUMENT_ERROR = "ADDING_CLIENT_ERROR",
    NO_USER_ERROR = "NO_USER_ERROR",
    MULTIPLE_USERS_ERROR = "MULTIPLE_USERS_ERROR",
    NO_GYM_SHEET_FOUND_ERROR = "NO_GYM_SHEET_FOUND_ERROR"
}