export enum SettingsButtonsEnum {
    DELETE_YOUR_ACCOUNT_BUTTON = "DELETE_YOUR_ACCOUNT_BUTTON",
    CHANGE_YOUR_PROFILE_DATA_BUTTON = "CHANGE_YOUR_PROFILE_DATA_BUTTON",
    OPEN_SOURCE_RESOURCES_BUTTON = "OPEN_SOURCE_RESOURCES_BUTTON"
}