export enum EnumErrors {
    ADDING_CLIENT_ERROR = "ADDING_CLIENT_ERROR",
    NO_CLIENT_FOUND_ERROR = "RETRIEVING_CLIENT_ERROR",
    MULTIPLE_CLIENTS_ERROR = "MULTIPLE_CLIENTS_ERROR",
    NO_PERSONAL_TRAINER_ERROR = "NO_PERSONAL_TRAINER_ERROR",
    MULTIPLE_PERSONAL_TRAINER_ERROR = "MULTIPLE_PERSONAL_TRAINER_ERROR"
}